# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('author', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20)),
                ('git_url', models.URLField(default=b'https://github.com/Boquete/electron-online-example.git')),
                ('destiny_git_url', models.URLField(default=b'https://github.com/Boquete/electron-online-example.git')),
                ('config_editor', models.TextField(blank=True)),
                ('config_file', models.URLField(blank=True, default=b'https://github.com/Boquete/electron-online-example/blob/master/electron_config.js')),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.App')),
            ],
        ),
    ]
